language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install -g karma-cli
  - npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3 # give xvfb some time to start
- rackup  # start a Web server
- sleep 3 # give Web server some time to bind to sockets, etc
script:
  - npm test
